version: "3.8"
services:
  svc-postgres:
    image: postgres:17
    container_name: pary-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - pary-nest-network
    env_file:
      - ./.env
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  # svc-nestjs:
  #   build:
  #     context: .
  #     dockerfile: nest.dev.Dockerfile
  #   env_file:
  #     - ./.env
  #   container_name: nest-service
  #   environment:
  #     DATABASE_HOST: ${DATABASE_HOST}
  #     DATABASE_PORT: ${DATABASE_PORT}
  #     DATABASE_USER: ${DATABASE_USER}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - svc-postgres
  #   networks:
  #     - pary-nest-network

networks:
  pary-nest-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
